# Generated by Django 4.0.5 on 2022-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_direction', models.CharField(max_length=200, verbose_name='Назва напрямку')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Напрямок',
                'verbose_name_plural': 'Напрямки',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doctor', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Опис')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('experience', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Досвід роботи')),
                ('direction', models.ManyToManyField(to='hospital.direction', verbose_name='Напрямок')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
            },
        ),
    ]
