# Generated by Django 4.0.5 on 2022-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direction',
            field=models.ManyToManyField(to='hospital.direction', verbose_name='Напрямки'),
        ),
    ]
