# Generated by Django 4.0.5 on 2022-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direction',
            field=models.ManyToManyField(related_name='direction', to='hospital.direction', verbose_name='Напрямок'),
        ),
    ]
